spring:
  profiles:
    include:
      - datasource
  application:
    name: user-api
  mvc:
    dispatch-options-request: true
  servlet:
    multipart:
      location: ${TEMPFILE_LOCATION}
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus